# Esercizio 1

Definire i  numpy array a=[1.2, 5.4, 6, 1.59] e b=[5.2, 1.2, 1.5, 2] ed eseguire le seguenti operazioni:
  - calcolare la radice quadrata degli elementi di a;
   - calcolare 𝑒xp(𝑎/2) ;
   - calcolare il vettore somma tra a e b ;
   - moltiplicare ogni elemento di a per il corrispondente elemento di b;
   - creare un vettore di valori uniformemente equispaziati tra 0 e 30 con passo  0.5;
   - creare un vettore di 100 valori uniformemente equispaziati tra 1 e 2.
   - usare linspace() per creare un numpy array 2x6 con prima riga di 6 valori uniformi compresi tra 10 e 20 e seconda riga 6 valori     
      uniformi compresi tra  20 e 10;
   - calcolare il prodotto scalare tra a e b;
   - creare la matrice A che ha come righe i vettori a e b ;
   - calcolare il prodotto scalare tra i due vettori a e b;
   - eseguire il prodotto della matrice A per il vettore b e assegnarlo ad y;
   - costruire una matrice diagonale D a partire dal vettore a;

In [11]:
import numpy as np

a = np.array([1.2, 5.4, 6, 1.59])
b = np.array([5.2, 1.2, 1.5, 2])

print("square root of elements of a = ", np.sqrt(a))
print("exp(a/2) = ", np.exp(a/2))
print("sum vector of a and b = ", a+b)
print("a*b element-wise = ", a*b)
print("vector of equispaced values between 0 and 30 with step 3 = ", np.arange(0, 30, 0.5))
print("vector of equispaced values between 1 and 2 = ", np.linspace(1, 2))
print(np.array([np.linspace(10, 20), np.linspace(20, 10)]))
print("scalar product a*b = ", np.dot(a, b))
A = np.array([a, b])
print("A = ", A)
y = np.dot(A, b)
print("y = ", y)
D = np.diag(a)
print("D = ", D)

square root of elements of a =  [1.09544512 2.32379001 2.44948974 1.26095202]
exp(a/2) =  [ 1.8221188  14.87973172 20.08553692  2.214441  ]
sum vector of a and b =  [6.4  6.6  7.5  3.59]
a*b element-wise =  [6.24 6.48 9.   3.18]
vector of equispaced values between 0 and 30 with step 3 =  [ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5
 14.  14.5 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5 20.  20.5
 21.  21.5 22.  22.5 23.  23.5 24.  24.5 25.  25.5 26.  26.5 27.  27.5
 28.  28.5 29.  29.5]
vector of equispaced values between 1 and 2 =  [1.         1.02040816 1.04081633 1.06122449 1.08163265 1.10204082
 1.12244898 1.14285714 1.16326531 1.18367347 1.20408163 1.2244898
 1.24489796 1.26530612 1.28571429 1.30612245 1.32653061 1.34693878
 1.36734694 1.3877551  1.40816327 1.42857143 1.44897959 1.46938776
 1.48979592 1.51020408 1.53061224 1.55102041 1.57142857 1.59183673
 1.6122449  1.63265306 1

# Esercizio 2

Costruire  i seguenti Numpy array 2d utilizzando il minor numero di istruzioni possibili

<img src="ese2.png" width="500">

In [30]:
import numpy as np

#creating the matrices
A = np.append(np.full((3, 3), 2), np.full((3, 1), 3), 1)
B = np.append(np.diagflat(np.full((1, 3), 2)), np.reshape(np.array([np.arange(1, 11)] * 3), (3, 10)), axis = 1)
C = np.diagflat(np.full((1, 4), -1), -1) + np.diagflat(np.full((1, 5), 2)) + np.diagflat(np.full((1, 4), -1), 1)
D = np.append(np.append(np.append(np.full((2,2), 2), np.full((2,2), 3), 1), np.zeros((2, 4)), 0), np.append(np.zeros((2, 2)), np.diagflat(np.full((1, 2), 5)), 1), 0)

print(np.append(np.append(np.full((2,2), 2), np.full((2,2), 3), 1), np.zeros((2, 4)), 0))
print(np.diagflat(np.full((1, 2), 5)))

#printing the matrices
print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)

[[2. 2. 3. 3.]
 [2. 2. 3. 3.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[5 0]
 [0 5]]
A = [[2 2 2 3]
 [2 2 2 3]
 [2 2 2 3]]
B = [[ 2  0  0  1  2  3  4  5  6  7  8  9 10]
 [ 0  2  0  1  2  3  4  5  6  7  8  9 10]
 [ 0  0  2  1  2  3  4  5  6  7  8  9 10]]
C = [[ 2 -1  0  0  0]
 [-1  2 -1  0  0]
 [ 0 -1  2 -1  0]
 [ 0  0 -1  2 -1]
 [ 0  0  0 -1  2]]
D = [[2. 2. 3. 3.]
 [2. 2. 3. 3.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 5.]]


# Esercizio 3

Calcolare la somma dei primi n numeri naturali dispari sia utilizzando un ciclo for che servendosi dell'istruzione sum di numpy.

In [34]:
import numpy as np
n = 24

forSum = 0
for i in range(1, n, 2):
    forSum = forSum + i
    
numpySum = np.sum(range(1, n, 2))

print(forSum)
print(numpySum)

144
144


# Esercizo 4

Scrivere una function Python per generare l'n-esimo termine (n > 2) della successione
di Fibonacci. Scrivere poi una function ricorsiva che risolva lo stesso problema
e confrontare i tempi di calcolo delle due functions per n = 24.

In [41]:
import numpy as np

def fibonacci(n):
    prev = 1
    curr = 1
    for i in range(2, n):
        tmp = curr
        curr = curr + prev
        prev = tmp
    return curr

def recursiveFibonacci(n):
    if(n == 2 or n == 1):
        return 1
    else:
        return recursiveFibonacci(n - 1) + recursiveFibonacci(n - 2)

n = 24

print(fibonacci(n))
print(recursiveFibonacci(n))

46368
46368
